use_frameworks!

target 'JDAStar_Example' do
  platform :ios, '9.0'
  pod 'JDAStar', :path => '../'

  target 'JDAStar_Tests' do
    inherit! :search_paths
  end
end

target 'JDAStar_MacOS_Example' do
  platform :macos, '10.0'
  pod 'JDAStar', :path => '../'
end
